### ISSUE TITLE
Timed Chess

### ISSUE THREAD

**Issue by nolanderc** [inda18plusplus/cnol-chess#3]
# Timed Chess

## Background
The king is getting old and is beginning to worry about when he is going to die. As such the king turned to you, the great sorcerer of time, for answers. As a master of the dark arts you knew exactly what you needed to do: create a countdown timer! 

## TODO
- [ ] Give each player a given amount of time to complete all their moves within.
- [ ] If a player runs out of time they should lose.
- [ ] When a player finishes a move they should be given an additional amount of time to their clock.
